Show the newest scanned instead longest live Pokémon as Recents
brusselopole/Worldopole pull request #136
Opened 2017-01-08 18:48 UTC by Arengo

## Description

The PR changes the most recents to show the newest scanned Pokémon by using the last_modified instead of disappear_time information of the DB.

## Motivation and Context

This PR focuses the issue #123, that the most recent list is not showing the real most recent Pokémon but those who are live for the longest time into the future. This resulted, especially for the mythic recents, into a list of 59 minute Mythics instead of new information when e. g. a new Dragonite is scanned but is only a 30 min spawn and therefore not shown in the most recent list. Also there will be more dynamic in the most recents with this change.

We have to be careful with hex-scanning Maps which over-scan some Pokémon, as well as -ss cluster spawns which also might be overscanned. If someone has an even better solution that also addresses this issue, please contribute :-)

## How Has This Been Tested?

locally

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2017-01-08 18:59 UTC, Arengo commented
[Issue] This is a general issue not only related to this PR. When more then one Pokémon is "new" between the update-interval of 5 seconds, the list is not 100% true because only the very recent is pushed.

2017-01-08 21:19 UTC, Obihoernchen requested changes

2017-01-08 21:19 UTC, Obihoernchen commented on core/process/data.loader.php
> +				   ORDER BY last_modified DESC LIMIT 0,12";
This is going to fail on newer mysql versions. See: http://piwigo.org/forum/viewtopic.php?pid=163884#p163884
You have to add last_modified to the SELECT DISTINCT part as well.

2017-01-08 21:19 UTC, Obihoernchen commented on core/process/data.loader.php
> +		$req		= "SELECT DISTINCT pokemon_id, disappear_time FROM pokemon ORDER BY last_modified DESC LIMIT 0,12";
This is going to fail on newer mysql versions. See: http://piwigo.org/forum/viewtopic.php?pid=163884#p163884
You have to add last_modified to the SELECT DISTINCT part as well.

2017-01-09 06:31 UTC, Arengo commented on core/process/data.loader.php
> +				   ORDER BY last_modified DESC LIMIT 0,12";
So we just add it in the requested variables? That's how I understand it from the link.

2017-01-09 07:37 UTC, Obihoernchen commented on core/process/data.loader.php
> +				   ORDER BY last_modified DESC LIMIT 0,12";
yep

2017-01-09 10:33 UTC, Arengo commented
^resolves your mentioned issue @Obihoernchen

2017-01-09 11:15 UTC, Obihoernchen approved these changes

2017-01-12 01:24 UTC, Obihoernchen commented
Merge this for now because it's way better than the current behaviour.
If @PoUpA comes up with an even better idea we will make another PR ;)

2017-01-12 01:24 UTC, merged