Display reCaptcha history on the dashboard (Credits to pokemonkiel.de)
brusselopole/Worldopole pull request #138
Opened 2017-01-12 00:11 UTC by Arengo

## Description

This PR provides a graph of encountered captchas during the past time and serves as a history for captcha activity.
The original code comes from the maintainer of pokemonkiel.de and is 99% of what you see in this PR. All credits go to him, I just serve with this PR to make it public to this project.

## Motivation and Context

Since this website relies on PokemonGo-Map as a core part to provide data, we have to go with the time and watch this project, too. All live Maps encounter reCaptcha at a medium or high rate today and most probably tomorrow. Since this is bounded to costs or user activity to solve them, this the amount of captcha produced ist a key value of interest. In conclusion we want it to be more transparent as well as being able to monitor and track it.

## How Has This Been Tested?

For some time on pokemonkiel.de where it works very fine. Additionally, locally on my fork.
Keep in mind that a working dashboard including a cron task is obligatory for this PR.

## Screenshots (if appropriate):
<img width="1194" alt="bildschirmfoto 2017-01-12 um 01 08 21" src="https://cloud.githubusercontent.com/assets/22680515/21871624/a532fd88-d863-11e6-91d5-68fdd1846f54.png">

## WIP
This PR is WIP and might need some additional edits to be merged to the current live branch in terms of code style or general compatibility. Also this could be a toggle-able feature as well since not everyone wants to make their captcha activity public since it can be redirected to the maps expenses (3$ per 1000 reCaptcha for example if 2captcha is used).
If you have any ideas, code or questions to improve or contribute, please feel free to comment.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2017-01-12 00:22 UTC, Arengo commented
Does Scrutinizer like me or is it just checking the very latest changes!?

2017-01-12 00:34 UTC, Arengo commented
^good boy

2017-01-12 01:22 UTC, Obihoernchen requested changes
Looks fine only locale support is missing

2017-01-12 01:40 UTC, Arengo commented
**To-Do**
- [ ] update the whole Dashboard layout for nice mobile appearance
- [ ] is red the light-right colour?
- [ ] make it toggle-able
- [ ] provide locales for this PR

2017-01-12 01:51 UTC, Obihoernchen commented on captcha-left.example.php
> -	$mysql->connect('#SYS_DB_HOST#', '#SYS_DB_USER#', '#SYS_DB_PSWD#', '#SYS_DB_NAME#', '3306');
At least you didn't include your DB credentials xD

2017-01-12 01:51 UTC, Arengo commented on captcha-left.example.php
> -	$mysql->connect('#SYS_DB_HOST#', '#SYS_DB_USER#', '#SYS_DB_PSWD#', '#SYS_DB_NAME#', '3306');
I was very, very careful :-D

2017-01-12 23:37 UTC, Arengo commented
It's not as nice as the shiny red, but the red signaled me instantly to look at it what is not certainly necessary since those are "only" captcha'd accounts not like banned or so.
Here is the un-shiny yellowish-orangeish you know:
<img width="1183" alt="bildschirmfoto 2017-01-13 um 00 35 37" src="https://cloud.githubusercontent.com/assets/22680515/21912786/6ad3f424-d928-11e6-8b4b-0b1e36f3e864.png">
Let me know if you have a nicer colour code.

2017-01-12 23:48 UTC, Obihoernchen requested changes

2017-01-12 23:48 UTC, Obihoernchen commented on pages/dashboard.page.php
>  				<canvas id="captcha" width="100%" height="25"></canvas>
you forgot to delete this ;)

2017-01-13 00:23 UTC, Obihoernchen approved these changes

2017-01-13 00:43 UTC, merged

2017-01-13 10:15 UTC, Arengo commented
Thank you, will be addressed!

2017-01-13 10:17 UTC, Obihoernchen commented
Ouh shit I missed this. Yes we have to change this to $time_offset