Refactored gym.maps.js let's see if scutinizer like it
brusselopole/Worldopole pull request #145
Opened 2017-01-14 12:40 UTC by PoUpA

## Description
Take this scruti !

## Motivation and Context
make scrutinizer green 🐶 

## How Has This Been Tested?
Localhost 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

2017-01-14 16:31 UTC, Obihoernchen commented
:dog;

2017-01-14 20:40 UTC, Obihoernchen requested changes

2017-01-14 20:40 UTC, Obihoernchen commented on core/json/.htaccess
> +</Files>
Please use Apache 2.4 access control: http://httpd.apache.org/docs/current/howto/access.html
Or make an if module ... and include both.

2017-01-15 01:56 UTC, Obihoernchen approved these changes

2017-01-15 01:57 UTC, Obihoernchen commented
Is there someone with 2captcha who could test this please?

2017-01-15 02:31 UTC, PoUpA commented
the result is this for me : 
![image](https://cloud.githubusercontent.com/assets/72618/21959804/2474de60-dad3-11e6-80fa-adf4c3313a41.png)

2017-01-15 02:40 UTC, merged

2017-01-15 02:40 UTC, Obihoernchen commented
I trust you and scruti :dog2: