Correct IV order to Attack/Defense/Stamina
brusselopole/Worldopole pull request #165
Opened 2017-01-29 20:35 UTC by klatterhans

## Description

As we told today we would change IV order to Attack/Defense/Stamina to synch with all pages and apps.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)

2017-01-29 21:14 UTC, Obihoernchen requested changes
Looks good, but gym page is missing.

2017-01-29 23:37 UTC, Obihoernchen approved these changes

2017-01-30 00:12 UTC, humer2000 commented
it would be great to have a working demo reflecting all the changes

2017-01-30 00:45 UTC, Obihoernchen commented
@humer2000 here you go: https://vserver.obihoernchen.net/pokemon_dev/

2017-01-30 00:51 UTC, Obihoernchen requested changes
Works expect a syntax error in trainer.content.js (see comment)

2017-01-30 00:51 UTC, Obihoernchen commented on core/js/trainer.content.js
> +	progressBar.append(
This is a syntax error. It have to be above the `$('<div>',`

2017-01-30 09:56 UTC, klatterhans commented on core/js/trainer.content.js
> +	progressBar.append(
Yes auf cause... should now be correct

2017-01-30 10:48 UTC, Obihoernchen approved these changes

2017-01-30 10:48 UTC, merged