Add total Pokemon counter to pokedex.page.php
brusselopole/Worldopole pull request #198
Opened 2017-02-20 22:48 UTC by Arengo

Please test.

- [x] New feature (non-breaking change which adds functionality)

2017-02-21 00:38 UTC, Arengo commented
Can't figure out why 🐶 doesn't like me

2017-02-21 06:51 UTC, Obihoernchen requested changes

2017-02-21 06:51 UTC, Obihoernchen commented on core/process/data.loader.php
> +        	$total	        = $data->total;
Indentation no wau wau :dog:

2017-02-21 06:51 UTC, Obihoernchen commented on pages/pokedex.page.php
> +			</p>*/
What's that? It's not a valid comment in html.

2017-02-25 00:46 UTC, merged

2017-02-25 00:47 UTC, Obihoernchen commented
I removed the POKEDEX_ULTRA_COMMONS string for now. We might add this in the future but in a proper way ;)