Improve localization <!--- Provide a general summary of your changes in the Title above -->
brusselopole/Worldopole pull request #218
Opened 2017-03-17 12:32 UTC by friscoMad

Added all missing strings to locales:

 * Trainer table headers
 * Pokemon table headers
 * Home ivs
 * Gym details

Improved localization of candies in pokedex for other languages

Improve general localization

Only UI changes
Working on http://map.neoseo.es

The only part that has not been tested is the IV info in home and top 50 pokemon in pokedex as my instance does not encounter pokemon.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2017-03-17 21:48 UTC, pokemonkiel commented
I like this. Thanks!
What about the "Today" and x "Days" at the bottom of each pokemon on trainer page?

2017-03-18 10:51 UTC, friscoMad commented
@pokemonkiel That part and the stats char inside pokedex are not that easy to translate as it is done via javascript, so we should pass that translated text somehow to javascript, it is not done in any other part and I wanted to leave this PR just for the obvious and simple changes.

2017-03-18 12:45 UTC, Obihoernchen commented
One +1 and I'll merge 👍 thx

2017-03-18 12:52 UTC, pokemonkiel commented
Okay I'll have a look at JS Translation later today. When I can figure it out fast we can add this in this commit

2017-03-18 13:12 UTC, pokemonkiel commented
@friscoMad I made a pull request into your fork with the changes.
In my tests it worked :)

2017-03-18 13:19 UTC, pki0 requested changes
Commit my PR to your branch please

2017-03-18 15:54 UTC, friscoMad commented
Ok, now it does include also the localization of pokemon info in trainers page thanks to @pokemonkiel 
I will not change anything else unlse requested, still somebody should test in an instance with wild pokemon encounters to check IV in home for the mythics and the table of best 50 wild pokemon in pokedex.

2017-03-20 18:58 UTC, pki0 approved these changes

2017-03-22 11:45 UTC, pokemonkiel commented
It's working for me in forced German and English language.
@friscoMad Please correct my two mistakes in German translation :)

2017-03-22 11:46 UTC, pki0 requested changes

2017-03-22 11:46 UTC, pokemonkiel commented on core/json/locales/DE/translations.json
> +"TODAY" "Heute",
Please add the :

2017-03-22 11:46 UTC, pokemonkiel commented on core/json/locales/DE/translations.json
> +"NOT_AVAILABLE" "Nicht verfügbar",
Please add the :

2017-03-22 12:48 UTC, pki0 approved these changes
Works now. Thanks!
Can be merged now in my opinion

2017-03-27 23:36 UTC, friscoMad commented
Ok sorry for the mess, I tried to rebase but I just messed everything, it is ready to be merged again.

2017-03-28 02:19 UTC, Obihoernchen commented
Merge ETA: next week. Sorry for the delay.

2017-03-28 09:52 UTC, pki0 requested changes
## Working:
- Trainer Pokemon tables IV bars
![image](https://cloud.githubusercontent.com/assets/21021281/24404107/2bc81166-13c0-11e7-9a99-db018a304928.png)

## Not working/Missing:
- home.page IV Bars (You missed aru.php)  
![image](https://cloud.githubusercontent.com/assets/21021281/24403629/04c51d68-13be-11e7-802d-7c206c8f697d.png)
https://github.com/brusselopole/Worldopole/blob/master/core/process/aru.php#L205
- Live Pokemon popups IV bars
![image](https://cloud.githubusercontent.com/assets/21021281/24403644/147c3a0c-13be-11e7-8efe-108149a5c847.png)
https://github.com/brusselopole/Worldopole/blob/master/core/js/pokemon.maps.js#L315

- Trainer graph on trainer page
![bildschirmfoto 2017-03-28 um 11 56 18](https://cloud.githubusercontent.com/assets/21021281/24399607/97a69898-13ad-11e7-891e-cf399b351af2.png)
https://github.com/brusselopole/Worldopole/blob/master/core/js/trainer.graph.js.php#L87

- Gym page popups IV bars
![image](https://cloud.githubusercontent.com/assets/21021281/24403666/29292abe-13be-11e7-93b7-0f3b0ac4c32e.png)
https://github.com/brusselopole/Worldopole/blob/master/core/process/aru.php#L527

- Pokemon.page Top tables: A /D /Sta   , non translated abbreviations
![bildschirmfoto 2017-03-28 um 11 54 42](https://cloud.githubusercontent.com/assets/21021281/24399549/68fd0676-13ad-11e7-89d6-6ac10bd13a7a.png)
https://github.com/brusselopole/Worldopole/blob/master/pages/pokemon.page.php#L298
https://github.com/brusselopole/Worldopole/blob/master/pages/pokemon.page.php#L340

- Pokemon.page Polarchart
![image](https://cloud.githubusercontent.com/assets/21021281/24403921/56152f4a-13bf-11e7-8705-ade143a880ff.png)
https://github.com/brusselopole/Worldopole/blob/master/core/js/pokemon.graph.js.php#L99

-Pokemon.page FB/Twitter Buttons:
![image](https://cloud.githubusercontent.com/assets/21021281/24403948/759e687c-13bf-11e7-88fa-3840ff244fca.png)
https://github.com/brusselopole/Worldopole/blob/master/pages/pokemon.page.php#L34

- Footer "Made in Brussels" (wish from Discord)
![image](https://cloud.githubusercontent.com/assets/21021281/24404028/caf19218-13bf-11e7-9fe8-6cd8e265821c.png)

https://github.com/brusselopole/Worldopole/blob/master/index.php#L131




**This was a quick testing.**

I'll add German translation after merge or Obi can do it. So we don't mess up shithub

2017-03-31 19:30 UTC, RamiroWincor commented
Sorry for the delay I think I can get it updated this weekend, I needed to do some work on RocketMap first so I could stabilize my server.

2017-03-31 20:00 UTC, friscoMad commented
Ok I did have a busy week trying to fix some things in my RM instance, I will work on this during this weekend to have it working asap.

2017-04-01 03:37 UTC, friscoMad commented
I think it is done, at least until someone finds something else that needs to translate.
I did not translate default gym UI (the ugly one) in gym map on purpouse. It can be done when it is fixed or removed.

As stated on the description my instance does not have encounters so please check that part before merging.

2017-04-02 17:25 UTC, Obihoernchen requested changes

2017-04-02 17:25 UTC, Obihoernchen commented on pages/trainer.page.php
> +		<h2 class="sub-title"><?= $locales->TRAINERS_GRAPH ?></h2>
Please change the key to TRAINER**S**_GRAPH in translation.json for all languages.

2017-04-02 17:25 UTC, Obihoernchen commented on pages/trainer.page.php
> +					<td colspan="6"><button id="loadMoreButton" class="btn btn-default hidden"><?= $locales->TRAINERS_LOAD_MORE ?></button></td>
Please change the key to TRAINER**S**_LOAD_MORE in translation.json for all languages.

2017-04-02 17:26 UTC, Obihoernchen commented
See comments above. Everything else seems to be fine I think 👍

2017-04-02 17:51 UTC, friscoMad commented
@Obihoernchen My bad, I have updated the translations missing.

2017-04-02 18:03 UTC, Obihoernchen approved these changes

2017-04-02 18:03 UTC, Obihoernchen commented
One more +1 and I'll merge.

2017-04-05 16:43 UTC, Obihoernchen commented
pls rebase <3

2017-04-06 02:11 UTC, friscoMad commented
Done, somebody pls +1 so it can merge or it will be a rebase nightmare, this PR touches almost all files 😭

2017-04-06 07:42 UTC, Obihoernchen approved these changes

2017-04-06 07:43 UTC, Obihoernchen commented
I'll not merge anything else before this.

2017-04-06 11:05 UTC, Obihoernchen commented on core/json/locales/EN/translations.json
> +"IV_STAMINA": "IV Stamina",
Please use `ATTACK`, `DEFENSE` and `STAMINA` only and just prepend `"IV "`. We don't have to translate this twice.

2017-04-06 11:09 UTC, Obihoernchen approved these changes

2017-04-06 11:10 UTC, Obihoernchen approved these changes

2017-04-06 11:21 UTC, merged