Simple nest/frequent spawn atlas
brusselopole/Worldopole pull request #221
Opened 2017-03-21 22:55 UTC by pokemonkiel

## Description
-Add a simple nest atlas.
-Map with spawns > 25% (>6 times) a day

## How Has This Been Tested?
- Locally with different forced languages

## Screenshots (if appropriate):
![image](https://cloud.githubusercontent.com/assets/21021281/24174608/cc3db508-0e91-11e7-8bb9-7e7440fd52e3.png)

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2017-03-23 08:46 UTC, Neayto commented
If sql_mode=only_full_group_by is activated, your code inside nests.cron.php doesnt´t work.

Error: Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'poke_gen2.pokemon.latitude' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

So i have to do 
mysql > SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

2017-03-24 07:28 UTC, mpw1337 commented
Eevee (133) can also have nests.

2017-03-27 11:12 UTC, pokemonkiel commented
@mpw1337 Are your sure? I did not found anything about that

@Neayto Thanks for the hint! I'll try to fix that

2017-03-27 11:52 UTC, pokemonkiel commented
@Neayto Error sould by fixed now. I have a result even with 

`SELECT @@sql_mode;
+--------------------+
| @@sql_mode         |
+--------------------+
| ONLY_FULL_GROUP_BY |
+--------------------+`

Would be great if you can test it. Thanks!

2017-03-27 12:25 UTC, mpw1337 commented
@pokemonkiel Yes, Eevee is definitely a nest pokemon. Even Spearow, Zubat and Sentret can have nests.
Current Eevee nest in our Park:
![image](https://cloud.githubusercontent.com/assets/1053226/24356110/e8d7e36c-12f8-11e7-9caf-b43b297de62b.png)
Link to Silphroad: [https://thesilphroad.com/atlas#16/49.4632/8.1776](https://thesilphroad.com/atlas#16/49.4632/8.1776)

2017-03-27 13:13 UTC, pokemonkiel commented
@mpw1337 Thanks. I'll add them now!

2017-03-27 15:20 UTC, mpw1337 commented
@pokemonkiel actually i think nearly every species, except dratini, mareep, larvitar, unown and evolved ones can have nests. But I don't have any proof atm.

2017-03-27 16:06 UTC, pokemonkiel commented
@mpw1337 No I think Pokemon like Pidgey, Weedle, Rattata and very common urban biomes can't be a nest at all. So I'm wondering about Spearow

2017-03-27 16:22 UTC, mpw1337 commented
@pokemonkiel 
You can take a look yourself here: http://pkmnstat.amsel-ap.de/pokemon/21 nest mitigation Nr.12 
Spearow Nest:
![image](https://cloud.githubusercontent.com/assets/1053226/24366577/d15fdf3e-1319-11e7-876c-ebdb3eead84d.png)
Before the nest mitigation to Spearow:
![image](https://cloud.githubusercontent.com/assets/1053226/24366621/f3a9247e-1319-11e7-8902-eb15bbcd369c.png)
and for Caterpie, Nest mitigation Nb. 10 http://pkmnstat.amsel-ap.de/pokemon/10 just compare it to the mitigation before.

2017-03-28 02:19 UTC, Obihoernchen commented
Merge ETA: next week. Sorry for the delay.

2017-03-28 07:19 UTC, pokemonkiel commented
@Obihoernchen No hurry :)

We have to discuss this nest thing a bit more:

@mpw1337 I think I got it. You can't figure out this as a Nest in my opinion!
Your Spearow "Nest" is in a non-nesting area so it can't be a nest. 

![bildschirmfoto 2017-03-28 um 09 17 45](https://cloud.githubusercontent.com/assets/21021281/24393204/790f8036-1397-11e7-9d84-a6b5dad556e9.png)

I have the same with Caterpie. But this is a non-nesting area, so no nest at all.

@Arengo Where did you get the nesting Pokemon List?

2017-03-28 08:00 UTC, mpw1337 commented
@pokemonkiel this "Kurpark" is definitely a nesting area.
Take a look at Mitigation nb 10 or 11 with Rhyhorn 
And gen2 Mitigation (16.02.2017) Growlithe
That's not because of a biome.

2017-03-28 12:06 UTC, Neayto commented
@pokemonkiel is working fine now 👍

2017-03-28 12:16 UTC, mean-jive commented
As far as I know, most 'mons can nest, like mpw1337 said; only a select few can't. The reason people don't think of pidgey etc nests, is cause you don't react to them when you encounter more than 1.

2017-03-28 13:23 UTC, Neayto commented
@pokemonkiel You should be able to define the pokemon id´s for the nest the total_pokemons  inside variables.json. So you can change it to your settings what you like.

And use it inside nests.cron.php
When i am at home i can look through it :)

2017-03-28 14:31 UTC, pokemonkiel commented
@Neayto Thanks. Glad to see that query is working now.
I added to variables string to decide pokemon_ids to show. Great idea. Thanks!

2017-03-28 16:13 UTC, z0n commented
I'm pretty sure that Swinub (#220) is also a nest Pokémon so it should be added to the default nest Pokémon list.
Before: ![image](https://cloud.githubusercontent.com/assets/7430908/24415439/c9e8efca-13e1-11e7-8961-a4eb6dff62db.png)

After: ![image](https://cloud.githubusercontent.com/assets/7430908/24415563/2676beb6-13e2-11e7-95e8-f28893f5f754.png)

2017-03-30 11:59 UTC, mean-jive commented
https://www.reddit.com/r/TheSilphRoad/comments/62cxzz/the_hopefully_ultimate_list_of_nonnesting_species/ - As much of a complete list I could find.

2017-04-02 23:40 UTC, Obihoernchen requested changes
Super awesome stuff!
Please add lat,long to the infowindow.

2017-04-03 15:57 UTC, Obihoernchen commented
We should exclude some very common pokemon like 21 and 161 from default nest_pokemon because nobody cares. They just clutter the map.

2017-04-03 16:01 UTC, Obihoernchen requested changes

2017-04-03 16:01 UTC, Obihoernchen commented on core/json/variables.examples.json
> +		"nest_pokemon"			:	"1, 4, 7, 21, 23, 25, 27, 29, 32, 37, 41, 43, 50, 56, 58, 60, 63, 66, 69, 74, 77, 79, 81, 84, 86, 90, 92, 95, 98, 100, 102, 104, 108, 109, 111, 114, 116, 120, 123, 124, 125, 126,
use an array instead (btw I removed 21 and 161).
Then we can use line breaks as well:

```json
[1, 4, 7, 21, 23, 25, 27, 29, 32, 37, 41, 43, 50, 56, 58, 60, 63, 66, 69, 74,
77, 79, 81, 84, 86, 90, 92, 95, 98, 100, 102, 104, 108, 109, 111, 114, 116,
120, 123, 124, 125, 126, 127, 133, 138, 140, 152, 155, 158, 161, 170, 183,
185, 187, 190, 191, 193, 194, 200, 202, 203, 204, 206, 207, 209, 211, 213, 
215, 216, 218, 223, 226, 227, 228, 231, 234, 241]
```

2017-04-03 16:30 UTC, Obihoernchen commented
What's the reason for using max?
`max(p.latitude) as latitude, max(p.longitude) as longitude,`

2017-04-05 16:40 UTC, Obihoernchen approved these changes

2017-04-05 16:41 UTC, Obihoernchen commented
I think it's fine for now!
One more +1 and I'll merge.

We can improve the pokemon_id list later on.

2017-04-06 08:06 UTC, pokemonkiel commented
@Obihoernchen. Could you please change included Pokemon IDs to excluded Pokemon IDs like on my very first commit.

This makes variables.json more readable and overall handling easier.
Change query from IN to NOT IN 

I think this is the better way

2017-04-06 08:38 UTC, Obihoernchen commented
@pokemonkiel I agree. Done :+1:

2017-04-06 11:46 UTC, friscoMad commented on core/cron/nests.cron.php
> +	$pokeid = $data->pokemon_id;
I think this is not needed

2017-04-06 12:22 UTC, pokemonkiel commented on core/cron/nests.cron.php
> +	$pokeid = $data->pokemon_id;
What do you mean exactly?

2017-04-06 12:26 UTC, friscoMad commented on core/cron/nests.cron.php
> +	$pokeid = $data->pokemon_id;
$pokeid var was not needed but @Obihoernchen did just fix that.

2017-04-06 12:45 UTC, Obihoernchen approved these changes

2017-04-06 14:35 UTC, friscoMad approved these changes

2017-04-06 17:40 UTC, merged

2017-04-07 12:19 UTC, mpw1337 commented on core/js/nests.maps.js.php
> +	$nest_file = file_get_contents('../json/nests.stats.json');
@pokemonkiel shouldn't this be:
`$nest_file = file_get_contents(SYS_PATH.'/core/json/nests.stats.json');`

2017-04-07 14:23 UTC, Obihoernchen commented on core/js/nests.maps.js.php
> +	$nest_file = file_get_contents('../json/nests.stats.json');
It doesn't matter

2017-04-07 19:15 UTC, mpw1337 commented on core/js/nests.maps.js.php
> +	$nest_file = file_get_contents('../json/nests.stats.json');
on my setup, which has limited htaccess rights it didn't work without the SYS_PATH