Add geolocation to Pokemon livemap/heatmap
brusselopole/Worldopole pull request #250
Opened 2017-04-15 08:37 UTC by pokemonkiel

## Description
- Add google geolocation to Pokemon livemap and heatmap
- Check if visitor is outside scanning area
- Geolocate only if inside scanning area

- Needs testing!

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2017-04-18 18:35 UTC, pokemonkiel commented
Btw: I'm back home and it works for me.
- outside scanning area map-center is location in variables.json
- inside scanning area map-center is geolocation

2017-04-19 17:28 UTC, Obihoernchen commented
Unfortunately this query is too heavy :(
```
SELECT MAX(latitude) AS max_latitude, MIN(latitude) AS min_latitude, MAX(longitude) AS max_longitude, MIN(longitude) as min_longitude FROM pokemon
```

2017-04-19 17:40 UTC, Obihoernchen requested changes

2017-04-19 17:40 UTC, Obihoernchen commented on core/js/pokemon.maps.js
> +		'async': false,
We shouldn't do anything with `'async': false`. It's deprecated and slow. Please move this to initMap() and make it async.

2017-04-19 17:40 UTC, Obihoernchen commented on core/process/aru.php
> +		$req 		 = "SELECT MAX(latitude) AS max_latitude, MIN(latitude) AS min_latitude, MAX(longitude) AS max_longitude, MIN(longitude) as min_longitude FROM pokemon";
pls query spawnpoint or scannedlocation table. This will be way faster (see my other comment).

2017-04-19 18:06 UTC, pokemonkiel commented on core/process/aru.php
> +		$req 		 = "SELECT MAX(latitude) AS max_latitude, MIN(latitude) AS min_latitude, MAX(longitude) AS max_longitude, MIN(longitude) as min_longitude FROM pokemon";
Hmm:

MariaDB [pokemonkiel]> SELECT MAX(latitude) AS max_latitude, MIN(latitude) AS min_latitude, MAX(longitude) AS max_longitude, MIN(longitude) as min_longitude FROM pokemon
+------------------+------------------+------------------+------------------+
| max_latitude     | min_latitude     | max_longitude    | min_longitude    |
+------------------+------------------+------------------+------------------+
| 54.5166280733962 | 53.9861774903964 | 10.6616758923218 | 9.48718048032647 |
+------------------+------------------+------------------+------------------+
1 row in set (0.06 sec)

But I can change it later, yes

2017-04-19 18:07 UTC, pokemonkiel commented on core/js/pokemon.maps.js
> +		'async': false,
I can try it. I needed synch load because we need the coordinates before the map is loading.

2017-04-19 18:15 UTC, Obihoernchen commented on core/js/pokemon.maps.js
> +		'async': false,
just  put the ajax request around anything which needs these coordinates.

2017-04-19 19:15 UTC, pokemonkiel commented on core/js/pokemon.maps.js
> +		'async': false,
But do we need ajax here?
Any other solution to get the data out of the aru.php?

2017-04-19 20:41 UTC, pokemonkiel commented on core/js/pokemon.maps.js
> +		'async': false,
Put 
```
		    $.ajax({
           'async': false,
           'type': "GET",
           'global': false,
           'dataType': 'json',
           'url': "core/process/aru.php",
           'data': {
           'request': "",
           'target': 'arrange_url',
           'method': 'method_target',
           'type' : 'pokemon_coordinates_area'

           }
           }).done(function(coordinates){
                   getArea(coordinates);
                   });
``` 
in initMap() works but only asynch: true not asynch:false

2017-04-23 01:02 UTC, Obihoernchen requested changes

2017-04-23 01:02 UTC, Obihoernchen commented on core/js/pokemon.maps.js
> +		}
The whole block from `if (navigator.geolocation) {` to this line have to be in `.done(function(coordinates) {`.

2017-04-23 01:03 UTC, Obihoernchen requested changes

2017-04-23 01:03 UTC, Obihoernchen commented on core/js/pokemon.maps.js
> +/** global: min_longitude */
This can be removed after my requested changes

2017-04-23 01:49 UTC, pokemonkiel commented
I think it's broken now :)

2017-04-23 09:55 UTC, Obihoernchen commented
:thumbsup:

2017-04-23 19:40 UTC, Obihoernchen approved these changes

2017-04-23 20:06 UTC, merged