[WIP|Help Needed] Pokemon Page improvements
brusselopole/Worldopole pull request #326
Opened 2017-11-14 14:49 UTC by 123FLO321

## Description
Added Pokemon Tree to Pokemon page [WIP]
Added Raid count to Pokemon page

## TODO
- [ ] Add all evolutions to pokedex.tree.json
- [ ] Center Pokemon on tree
- [ ] Remove double separator line below tree

## How Has This Been Tested?
Raids working.
Tree working but help needed

## Screenshots (if appropriate):

Raid Count:
<img width="1182" alt="sc 1" src="https://user-images.githubusercontent.com/1949038/32786014-27b23220-c953-11e7-8489-8b48850bef77.png">

Tree:
<img width="1067" alt="sc 2" src="https://user-images.githubusercontent.com/1949038/32786021-297c9b36-c953-11e7-89bc-a403425e3be6.png">

## Types of changes
- [X] New feature (non-breaking change which adds functionality)

2017-11-14 16:04 UTC, michikrug commented
I think the raid stuff will not work properly, because RM only stores current raids for each gym.
So if a gym gets a new raid the old data is gone.

The evolution tree will maybe work also without a new file, because the candy requirements are stored in the pokedex file already.

2017-11-14 16:31 UTC, 123FLO321 commented
@michikrug 
1. True. Will add a new cron to fix that.
2. That would be possible, but I think it's cleaner this way. (and potentially faster)

2017-11-17 02:15 UTC, ChrisCoX1988 commented
I try to test it and the tree works without problems at all. And the raid too but i must wait to tomorrow for new raids. :D Nice Work.

2017-11-20 00:25 UTC, ChrisCoX1988 commented
Result runs without Problems at me.

2017-11-28 11:27 UTC, Obihoernchen commented
+1 and I'll merge

2017-12-08 16:29 UTC, alone23 commented
Tested and works fine!

2017-12-08 17:22 UTC, Obihoernchen commented
Please rebase :)

2017-12-08 17:33 UTC, 123FLO321 commented
done @Obihoernchen

2017-12-08 19:43 UTC, Obihoernchen requested changes

2017-12-08 19:43 UTC, Obihoernchen commented on pages/pokemon.page.php
> +								<p class="pkmn-name"><a href="<?= $link ?>">#<?= sprintf('%03d<br>%s', $tree_pokemon->id, $tree_pokemon->name) ?></a></p>
$link does not work if Worldopole is installed in a subdirecotry

2017-12-10 19:39 UTC, javisabalete commented
Works fine! Great job!

2017-12-11 16:18 UTC, Obihoernchen approved these changes

2017-12-11 16:18 UTC, merged