Adsense support
brusselopole/Worldopole pull request #355
Opened 2018-01-27 00:09 UTC by javisabalete

## Description
Adsense example code provided following analytics example code

## Motivation and Context

Many websites are using ads to fund themselves. It's interesting to have a space for them.

## How Has This Been Tested?

prod instance

## Screenshots (if appropriate):
![screen shot 2018-01-27 at 00 37 16](https://user-images.githubusercontent.com/8037941/35465617-8c695e76-02fd-11e8-8b26-6df57474d287.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2018-01-27 00:51 UTC, Obihoernchen requested changes

2018-01-27 00:51 UTC, Obihoernchen commented on index.php
> +					if (is_file("adsense.php")) {
Please move the if up. We don't need the additional div if adsense is not used.

2018-01-27 20:51 UTC, michikrug commented
I would rather recommend to use the page_level_ads that are automatically inserted in all the pages by including the adsense script (like stated below) only in the head.
Same applies for analytics.

`<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>(adsbygoogle = window.adsbygoogle || []).push({ google_ad_client: "ca-pub-xxx", enable_page_level_ads: true });</script>`

2018-01-27 22:58 UTC, javisabalete commented
Page level ads is only for mobile browsers, however this PR show banners at desktop and mobile browsers

2018-01-27 23:07 UTC, michikrug commented
This is not true at all. Page level ads perfectly serve banner ads also on desktop.

2018-01-27 23:16 UTC, javisabalete commented
![captura de pantalla 2018-01-28 a las 0 16 07](https://user-images.githubusercontent.com/8037941/35477315-7b931b50-03c0-11e8-9617-045efeb036c2.png)

Chrome last version (MacOS)

2018-01-27 23:21 UTC, michikrug commented
This is perfectly true, because the special type of anchor ads is only for mobile browsers.
But page level ads support all types of ads and choose those which fit the best.

2018-01-30 02:43 UTC, javisabalete commented
Ooops, I can't see it

![screenshot from 2018-01-30 03-40-39](https://user-images.githubusercontent.com/8037941/35545454-7aebb206-056f-11e8-9afe-aa090be2bfa1.png)

:1st_place_medal:

2018-01-30 14:35 UTC, michikrug commented
Oh. This is strange. I honestly have no idea why you do not have the switch.

Only on my map I use a fixed ad slot.

2018-02-27 12:14 UTC, Obihoernchen commented
@javisabalete please check if we can use page level ads? Maybe there is an option you have to activate?

2018-02-27 12:26 UTC, michikrug commented
The newest stuff is called "Auto ads" and will replace Page-level ads.
They are included/used exactly as page-level ads.

https://support.google.com/adsense/answer/7478040?hl=en#

2020-10-14 09:37 UTC, closed without merging