Menu with submenu
brusselopole/Worldopole pull request #368
Opened 2018-03-27 00:13 UTC by Student1978

## Description
Extended by submenu functionality

![grafik](https://user-images.githubusercontent.com/36744360/37939645-43def93c-3164-11e8-83ad-20c7f226abdc.png)

## Motivation and Context
I have many items on the menu, and need submenus

## How Has This Been Tested?
Work at my Worldopole instance

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2018-03-27 00:39 UTC, 123FLO321 requested changes
Haven't tested it yet but looks good otherwise.

2018-03-27 00:39 UTC, 123FLO321 commented on index.php
> +function menuitems($menu, $level) {
We don't have functions in the index.php
You should probably move it to functions.php until it gets refactored.
And menuitems to printMenuitems or something similar so we can understand what the function does more easily.

2018-04-18 12:39 UTC, Obihoernchen requested changes
Please change the text color back to grey.
Thank you :)

2018-04-23 08:31 UTC, Obihoernchen approved these changes

2018-04-23 08:31 UTC, merged