German Translation
brusselopole/Worldopole pull request #66
Opened 2016-09-12 09:57 UTC by krummrey

## Description
Added german translation to translations.json and a Pokelist in german

## Motivation and Context
Not implemented yet

## How Has This Been Tested?
Runs on my site without problems

## Screenshots (if appropriate):

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2016-09-12 10:07 UTC, 56k-amaury commented
Thanks for trad! 
I'll merge it tonight as it looks that there's some conflict 


👍

2016-09-12 11:58 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Find all collected and proccessed data about PokémonGo in %s : nests, stats, frequency, ... Learn when and where to look for the Pokémon you're missing."
translation missing

2016-09-12 11:58 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Lock-Module"
"Lockmodule"

2016-09-12 11:58 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "This website or the authors have no relationship with Niantic, Nintendo or other any Pokémon Go responsible."
translation missing

2016-09-12 11:58 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "<p>Icons designed by <a href='http://www.flaticon.com/packs/packs/pokemon-go/''>Roundicons Freebies</a> for <a href='http://www.flaticon.com'>Flaticon</a>. Font icons provided by <a href='ht
translation missing

2016-09-12 11:58 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "<p>Pokémon Go is ©2016 Niantic, Inc. ©2016 Pokémon. ©1995–2016 Nintendo / Creatures Inc. / GAME FREAK inc.</p><p>Pokémon and Pokémon character names are trademarks of Nintendo.</p><p>Other t
translation missing

2016-09-12 11:59 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "<strong>Pokédex</strong> Übersicht<br><small>Gotta catch 'em all!</small>"
translation missing

2016-09-12 11:59 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Follow the conquest"
translation missing

2016-09-12 11:59 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Valor, Mystic or Instinct? Who will win the fight?"
translation missing

2016-09-12 12:00 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Famile"
"Familie"

2016-09-12 12:00 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "MOAR <strong>DATA</strong> MOAAAAR"
translation missing

2016-09-12 12:01 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Aktive Lock-Module"
"Aktive Lockmodule"

2016-09-12 12:01 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Mystic Prestige Average"
translation missing

2016-09-12 12:01 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Valor Prestige Average"
translation missing

2016-09-12 12:01 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Instinct Prestige Average"
translation missing

2016-09-12 12:01 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Mystic Gym Owned"
translation missing

2016-09-12 12:01 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Valor Gym Owned"
translation missing

2016-09-12 12:01 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Instinct Gym Owned"
translation missing

2016-09-12 12:02 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Lured Pokestop"
translation missing

2016-09-12 12:02 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Instinkt"
"Intuition"

2016-09-12 12:02 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Mystic"
Wagemut

2016-09-12 12:02 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Mystic"
Weisheit

2016-09-12 12:04 UTC, NHGRisk commented
If you don't wanna correct the "mistakes" i can do it this evening
danke für die arbeit dennoch!

2016-09-12 14:26 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Instinkt - Prestige Durchschnitt"
Intuition

2016-09-12 14:27 UTC, NHGRisk commented on core/json/translations.json
> +		"DE": "Arenen von Tem Instinkt"
Intuition

2016-09-13 07:57 UTC, Obihoernchen commented
Please add de to `core/json/variables.examples.json` as well :)

2016-09-14 08:08 UTC, krummrey commented
I made a bunch of changes in my repo. Will they show up here or do I have to do something so that this request is updated?

2016-09-14 11:16 UTC, NHGRisk commented
@krummrey i think u gotta update it manually

2016-09-14 12:47 UTC, Obihoernchen commented
@krummrey they show up automatically. You don't have to do anything except pushing the changes to your repo. 
Please git pull the latest code from original repo and resolve merge conflicts 👍

2016-09-15 20:20 UTC, brusselopole commented
This branch has conflicts that must be resolved

@NHGRisk could you check please?

2016-09-16 15:01 UTC, Obihoernchen requested changes
Do not merge yet! 

There are still issues with some translations. 
Please add NHGRisks comments. But then there are still some issues left. For example it must be team "Intuition".

2016-09-16 19:53 UTC, NHGRisk commented
I updated & corrected it https://github.com/brusselopole/Worldopole/pull/68

2016-09-17 00:30 UTC, Obihoernchen commented
Let's use #68 cause it has no merge conflicts and more fixes. 
Thank you @krummrey for the base!

2016-09-17 00:30 UTC, closed without merging